import { BRProfileImport } from "../Components/BruteRatelC4/BRProfileImport";
import { CSProfileCreate } from "../Components/CobaltStrike/CSProfileCreate";
import { CSProfileCreateFromHttp } from "../Components/CobaltStrike/CSProfileCreateFromHttp";
import { CSProfileEdit } from "../Components/CobaltStrike/CSProfileEdit";
import { CSProfileExport } from "../Components/CobaltStrike/CSProfileExport";
import { CSProfileImport } from "../Components/CobaltStrike/CSProfileImport";
import { CSProfileTest } from "../Components/CobaltStrike/CSProfileTest";
import { TopBlockMetaName } from "../Plugins/CobaltStrike/CSMetadataTypes";
import { CSValidate } from "../Plugins/CobaltStrike/CSProfileValidation";
import { AppFlow } from "./Common";

export interface Section {
    title: string;
    description: string;
}

export type ProfileChangedCb = (profile: any) => void;
export type SetStepCb = (step: AppFlow) => void;

/* App flow related props & views definitons */
export interface IC2BasicFlowProps extends Section {
    profile: any;
    navigateTo: SetStepCb;
}

export interface IC2EditProps extends IC2BasicFlowProps {
    onProfileChanged: ProfileChangedCb;
}

export interface EditView extends Section {
    view: (props: IC2EditProps) => JSX.Element;
}

export interface IC2TestProps extends IC2BasicFlowProps { }

export interface TestView extends Section {
    view: (props: IC2TestProps) => JSX.Element;
}

export interface IC2ExportProps extends IC2BasicFlowProps { }

export interface ExportView extends Section {
    view: (props: IC2ExportProps) => JSX.Element;
}

export type MessageLevel = "info" | "warning" | "error";
export const MessageLevelDisplayName = {
    "info": "Info",
    "warning": "Warning",
    "error": "Error"
}

export interface ValidationMessage {
    block?: TopBlockMetaName; //TODO: Refactor into generic component (e.g. "meta" that can be casted like profile is)
    level: MessageLevel;
    message: string;
    items?: string[];
}

export type ValidateCb = (profile: any) => ValidationMessage[];

export interface IC2Provider {
    name: string;
    importers: IC2Importer[];
    editView: EditView;
    testView: TestView;
    exportView: ExportView;
    validator?: ValidateCb;
}


export interface IC2ImporterProps {
    onImported: (profile: any) => void;
}

export interface IC2Importer {
    name: string,
    view: (props: IC2ImporterProps) => JSX.Element;
}

const DummyView = ({ profile }: IC2TestProps): JSX.Element => {
    return <>{JSON.stringify(profile)}</>
};

export const CobaltStrike: IC2Provider = {
    name: "Cobalt Strike",
    importers: [
        {
            name: "Use existing profile",
            view: CSProfileImport
        },
        {
            name: "Create profile from HTTP traffic",
            view: CSProfileCreateFromHttp
        },
        {
            name: "Create new",
            view: CSProfileCreate
        }
    ],
    editView: {
        title: "CS Malleable Profile Editing",
        description: "Here you can edit your Cobalt Strike malleable profile and add, remove, and configure blocks.",
        view: CSProfileEdit
    },
    testView: {
        title: "CS Malleable Profile Test",
        description: "Now it's time to evaluate with your profile. In this step you can inspect HTTP requests and responses generated by your profile.",
        view: CSProfileTest
    },
    exportView: {
        title: "CS Malleable Profile Export",
        description: "Here's your exported profile - use it responsibly!",
        view: CSProfileExport
    },
    validator: CSValidate
}

export const BruteRatelC4: IC2Provider = {
    name: "Brute Ratel C4",
    importers: [
        {
            name: "Use existing profile",
            view: BRProfileImport
        }
    ],
    editView: {
        title: "BR Malleable Profile Editing",
        description: "Here you can edit your Brute Ratel C4 malleable profile.",
        view: DummyView
    },
    testView: {
        title: "BR Malleable Profile Test",
        description: "Now it's time to evaluate with your profile. In this step you can inspect HTTP requests and responses generated by your profile.",
        view: DummyView
    },
    exportView: {
        title: "BR Malleable Profile Export",
        description: "Here's your exported profile - use it responsibly!",
        view: DummyView
    }
}